### ISSUE TITLE
I broke tests because of Arbitrary

### ISSUE THREAD

**Issue by mengwong** [smucclaw/dsl#213]
I need help … I upgraded the `baby-l4` repo and many of the dependencies for `natural4` to work with LTS20.2 and GHC 9.2.5, but something in the GHC8-to-GHC9 upgrade caused some breakage in `test/Spec.hs`. It has something to do with Arbitrary:

```
/Users/mengwong/src/smucclaw/dsl/lib/haskell/natural4/test/Spec.hs:1:1: error:
    solveWanteds: too many iterations (limit = 4)
...

                                  bf0)’ from being solved.
      Probable fix: use a type annotation to specify what ‘af0’,
                                                          ‘bf0’ should be.
      These potential instances exist:
        instance (FiniteSumElem self b, Finite self a ~ 'False,
                  Finite self b ~ 'True) =>
                 FiniteSum self a b 'False 'True
          -- Defined in ‘Test.QuickCheck.Arbitrary.Generic’
        instance (FiniteSumElem self a, Finite self a ~ 'True,
                  Finite self b ~ 'False) =>
                 FiniteSum self a b 'True 'False
          -- Defined in ‘Test.QuickCheck.Arbitrary.Generic’
        instance (FiniteSumElem self a, FiniteSumElem self b,
                  Finite self a ~ 'True, Finite self b ~ 'True) =>
                 FiniteSum self a b 'True 'True
          -- Defined in ‘Test.QuickCheck.Arbitrary.Generic’
    • In the expression: genericArbitrary
      In an equation for ‘arbitrary’: arbitrary = genericArbitrary
      In the instance declaration for ‘Arbitrary MyToken’
    |
233 |   arbitrary = genericArbitrary
    |               ^^^^^^^^^^^^^^^^
Progress 1/2
```

@anka-213 I don't know if @kharus and I will be able to solve this in finite time so could I ask you to come take a look? If you've been keeping up with the changelog and release notes for GHC this might be a super quick fix, but I haven't been keeping up.

**Comment by mengwong** [comment]
https://gitlab.haskell.org/ghc/ghc/-/issues/22516

**Comment by mengwong** [comment]
I believe we now have
```
-ghc-options: -Wall -Wno-missed-extra-shared-lib
+ghc-options: -Wall -Wno-missed-extra-shared-lib -fconstraint-solver-iterations=10
```

added somewhere; when GHC fixes this upstream, we can remove that.

**Comment by anka-213** [comment]
did you solve this issue or do you still need my help?
